Rails.application.routes.draw do
  # Authentication (generated by Rails 8 auth generator)
  resource :session
  resources :passwords, param: :token

  # User registration (sign-up)
  resource :registration, only: [ :new, :create ]

  # Account settings
  resource :settings, only: [ :show, :update ]

  # Onboarding (first-time user wizard)
  namespace :onboarding do
    resource :project,    only: [ :new, :create ]
    resource :template,   only: [ :new, :create ]
    resource :adapter,    only: [ :new, :create ]
    resource :completion, only: [ :new, :create ]
  end

  # Projects
  resources :projects, only: [ :index, :new, :create, :edit, :update ] do
    resource :switch, only: [ :create ], module: :projects, controller: "switches"
    member do
      post :emergency_stop
    end
  end

  # Invitations (scoped to active project via Current.project)
  resources :invitations, only: [ :index, :new, :create ]

  # Invitation acceptance (public, token-based)
  resources :invitation_acceptances, only: [ :show, :update ], param: :token

  # Role Categories (scoped to active project via Current.project)
  resources :role_categories

  # Org Chart & Roles (scoped to active project via Current.project)
  resources :roles do
    resources :role_skills, only: [ :create, :destroy ]
    resources :heartbeats, only: [ :index ]
    resources :role_hooks
    resources :role_runs, only: [ :index, :show ] do
      member do
        post :cancel
      end
    end

    scope module: :roles do
      resource :activity,    only: [ :create ]
      resource :pause,       only: [ :create, :destroy ]
      resource :termination, only: [ :create ]
      resource :approval,    only: [ :create, :destroy ]
    end

    member do
      post :hire, to: "role_hirings#create"
    end
  end
  get "org_chart", to: redirect("/roles")

  # Role Templates (browse and apply department templates)
  resources :role_templates, only: [ :index, :show ] do
    member do
      post :apply
    end
  end

  # Skills (scoped to active project via Current.project)
  resources :skills do
    resources :skill_documents, only: [ :create, :destroy ]
  end

  # Documents (scoped to active project via Current.project)
  resources :documents
  resources :document_tags, only: [ :index, :create, :destroy ]

  # Tasks (scoped to active project via Current.project)
  resources :tasks do
    resources :task_documents, only: [ :create, :destroy ]
    resources :messages, only: [ :create ]
    resource :approval, only: [ :update ], controller: "tasks/approvals"
    resource :rejection, only: [ :update ], controller: "tasks/rejections"
    member do
      post :delegate, to: "task_delegations#create"
      post :escalate, to: "task_escalations#create"
      post :ask_question, to: "task_questions#create"
    end
    collection do
      resource :bulk_update, only: [ :create, :destroy ], controller: "tasks/bulk_updates"
    end
  end

  # Goals (scoped to active project via Current.project)
  resources :goals do
    resource :recurrence, module: :goals, only: [ :destroy ]
  end

  # Notifications (scoped to active project via Current.project)
  resources :notifications, only: [ :index ] do
    member do
      patch :mark_read
    end
    collection do
      post :mark_all_read
    end
  end

  # Audit Log (scoped to active project via Current.project)
  resources :audit_logs, only: [ :index ]

  # Config Versions (version history and rollback for Role)
  resources :config_versions, only: [ :index, :show ] do
    member do
      post :rollback
    end
  end

  # Dashboard (project command center — root landing page)
  resource :dashboard, only: [ :show ], controller: "dashboard"

  # Documentation (public)
  get "docs", to: "docs#index", as: :docs
  namespace :documentation, path: "docs" do
    resources :projects, only: [ :index ]
    resources :roles, only: [ :index ]
    resources :adapters, only: [ :index ]
    resources :tasks, only: [ :index ]
    resources :skills, only: [ :index ]
  end
  get "docs/*path", to: "docs#show", as: :docs_page

  # Health check - used by load balancers and uptime monitors
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end
